# Generated by Django 4.2.2 on 2023-06-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('st', 'Studying'), ('wk', 'Working'), ('re', 'Retired'), ('ml', 'Millionaire'), ('no', 'Nothing')], default='no', max_length=50)),
                ('salary', models.IntegerField()),
                ('about', models.TextField(blank=True, default='')),
            ],
        ),
    ]
